package co.btg.FondosApp.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Fondos")
public class Fondo {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String fondoId;

    @DynamoDBAttribute
    private String categoriaFondo;

    @DynamoDBAttribute
    private String montoMinimoVinculacion;

    @DynamoDBAttribute
    private String nombreFondo;
}
