package co.btg.FondosApp.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Fondos")
public class Fondo {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String fondoId;

    @DynamoDBAttribute
    private String categoriaFondo;

    @DynamoDBAttribute
    private Integer montoMinimoVinculacion;

    @DynamoDBAttribute
    private String nombreFondo;
}
